### ISSUE TITLE
[Bug] Screen recording doesn't show the correct time and it freezes and becomes useless after ending the recording.

### ISSUE THREAD

**Issue by theoccurrence** [34306/mineland#2]
Title. It will always display 00:00, and after recording the island freezes in recording mode (with the red dot)

**Comment by 34306** [comment]
Hmmm, mine is totally fine. I'll checking it soon
![IMG_0018](https://github.com/34306/mineland/assets/79745143/460227c7-0d68-4127-aeed-87ba35297e73)

**Comment by theoccurrence** [comment]
> Hmmm, mine is totally fine. I'll checking it soon
> 
> ![IMG_0018](https://github.com/34306/mineland/assets/79745143/460227c7-0d68-4127-aeed-87ba35297e73)
> 
> 

It's like this for me: https://github.com/34306/mineland/assets/16444679/4441f076-4282-4a68-ab82-90688ef02ad7

**Comment by 34306** [comment]
> > Hmmm, mine is totally fine. I'll checking it soon
> > ![IMG_0018](https://private-user-images.githubusercontent.com/79745143/303515255-460227c7-0d68-4127-aeed-87ba35297e73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzcxMjEsIm5iZiI6MTcwNzQzNjgyMSwicGF0aCI6Ii83OTc0NTE0My8zMDM1MTUyNTUtNDYwMjI3YzctMGQ2OC00MTI3LWFlZWQtODdiYTM1Mjk3ZTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDAwMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiN2ZkNDg3MTU5MjY3ZWQwOTVmYzRkMjhlMTBlZDllZjVlMmM1MDI3ZjA3ODk2M2M4YTBhNzc0M2YxODI0MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aVX2-VXC9BiQ1wdoPuVojOj5b6T6oK5s_prLITdYdlQ)
> 
> It's like this for me: https://github.com/34306/mineland/assets/16444679/4441f076-4282-4a68-ab82-90688ef02ad7

Bro... 00:00 is the time recording pause... you pause it right after you start it 🤨

**Comment by theoccurrence** [comment]
> > > Hmmm, mine is totally fine. I'll checking it soon
> 
> > > ![IMG_0018](https://private-user-images.githubusercontent.com/79745143/303515255-460227c7-0d68-4127-aeed-87ba35297e73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzcxMjEsIm5iZiI6MTcwNzQzNjgyMSwicGF0aCI6Ii83OTc0NTE0My8zMDM1MTUyNTUtNDYwMjI3YzctMGQ2OC00MTI3LWFlZWQtODdiYTM1Mjk3ZTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDAwMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiN2ZkNDg3MTU5MjY3ZWQwOTVmYzRkMjhlMTBlZDllZjVlMmM1MDI3ZjA3ODk2M2M4YTBhNzc0M2YxODI0MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aVX2-VXC9BiQ1wdoPuVojOj5b6T6oK5s_prLITdYdlQ)
> 
> > 
> 
> > It's like this for me: https://github.com/34306/mineland/assets/16444679/4441f076-4282-4a68-ab82-90688ef02ad7
> 
> 
> 
> Bro... 00:00 is the time recording pause... you pause it right after you start it 🤨

There is no way to "pause" a screen recording, but in case it wasn't clear what I'm talking about, here is a better demonstration: (imgur link due to video length) https://imgur.com/a/exvOyPH

You can even see it saved the 25 sec video. This isn't the issue. The issue is the dynamic island only ever displaying 00:00 and not returning back to normal after the recording.

Here look, I can even have recording and airdrop at the same time, because the left side of the dynamic island is frozen in the recording state:

![image](https://github.com/34306/mineland/assets/16444679/6d134b51-90ea-4ef4-88e1-8ef1a35f7de5)

**Comment by theoccurrence** [comment]
This might have nothing to do with your tweak. I just realized this also happens without your teak just with DynamicCow active.
