### ISSUE TITLE
[Bug] Dynamic island flickers on homescreen (and sometimes in apps as well) before disappearing

### ISSUE THREAD

**Issue by theoccurrence** [34306/mineland#3]
I have yet to test if this is an incompatibility with another tweak. Will test and update in a comment.

**Comment by 34306** [comment]
That blinks seems a bug from iOS, I mean that's iOS stock bug. That's how Dynamic Island work. I think i'll try to hide it without the blinks soon, require a little more patch

**Comment by theoccurrence** [comment]
> That's how Dynamic Island work.

Odd. Just in case we're talking about different things, I'm talking about this:

https://github.com/34306/mineland/assets/16444679/c281621e-ff80-42c5-9e7e-13b28ddba68d

Also, blinking and cut in half dynamic island in app switcher:

https://github.com/34306/mineland/assets/16444679/65e27221-53f4-4c99-be78-766f1917d243

**Comment by 34306** [comment]
Imagine that's spinlock panic. idk but apple build that's. I can't do anything since the dynamic island pill is not removable.
I'll try to fix that by another kind... i don't think that should work

**Comment by theoccurrence** [comment]
> Imagine that's spinlock panic. idk but apple build that's. I can't do anything since the dynamic island pill is not removable.
> 
> I'll try to fix that by another kind... i don't think that should work

Apple doing Apple things. Good luck

**Comment by 34306** [comment]
Fixed in lastest release

**Comment by theoccurrence** [comment]
> Fixed in lastest release

Amazing! Thank you
