### ISSUE TITLE
[Bug] Unlocking the phone directly into an app, instead of home screen, freezes the dynamic island until you scroll the screen.

### ISSUE THREAD

**Issue by theoccurrence** [34306/mineland#4]
Title. The dynamic island disappears on its own on the homescreen after unlocking, but in apps it will stay there until you scroll the screen.

**Comment by theoccurrence** [comment]
Sometime it's only part of the island, sometimes it's the whole island that stays on screen. Seems to be app dependent.

https://github.com/34306/mineland/assets/16444679/b64c1f86-0a09-431b-8fdd-dfbc2163eed9

**Comment by 34306** [comment]
Fixed in lastest release
